services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    depends_on:
      database:
        condition: service_healthy
    ports: [ "80:80" ]
    environment:
      # PHP level cache
      PHP_OPCACHE_ENABLE: "false"
      PHP_APCU_ENABLE: 0
      # Logs
      CADDY_LOG_OUTPUT: "file var/log/caddy.log"
      CADDY_LOG_LEVEL: "INFO"
      FPM_ACCESS_LOG: "/var/log/php-fpm.access.log"
      FPM_ERROR_LOG: "/var/log/php-fpm.error.log"
      FPM_LOG_LEVEL: "notice"
      PHP_ERROR_LOG: "/var/log/php.error.log"
      PHP_LOG_LEVEL: "E_ALL"
      # Application
      APP_ENV: "dev"
      APP_SECRET: "a9806d99cd5c1503d8af30c963c9411f"
      # External services
      DATABASE_URL: "mysql://user:password@database:3306/blog"
    volumes:
      - { type: bind, source: ., target: /app }
  database:
    image: 'mysql:8.4'
    ports: ["3306:3306"]
    environment:
      MYSQL_ROOT_PASSWORD: "password"
      MYSQL_DATABASE: "blog"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=password --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
